from dotenv import load_dotenv
import os

load_dotenv()

OLLAMA_URL = os.getenv('GOVERNOR_OLLAMA_URL', 'http://localhost:11434')
OLLAMA_MODEL = os.getenv('GOVERNOR_OLLAMA_MODEL', 'qwen2.5-coder')

OLLAMA_URL_TO_BENCHMARK = os.getenv('GOVERNOR_OLLAMA_URL_TO_BENCHMARK', OLLAMA_URL)
OLLAMA_MODEL_TO_BENCHMARK = os.getenv('GOVERNOR_OLLAMA_MODEL_TO_BENCHMARK', OLLAMA_MODEL)

OLLAMA_URL_VERIFIER = os.getenv('GOVERNOR_OLLAMA_URL_VERIFIER', OLLAMA_URL)
OLLAMA_MODEL_VERIFIER = os.getenv('GOVERNOR_OLLAMA_MODEL_VERIFIER', OLLAMA_MODEL)

